guard against AttributeError exception in get_device_list
lineageos-infra/updater pull request #17
Opened 2018-04-15 10:04 UTC by Stricted

when you provide an empty builds.json
````
[]
```
then the whole updater will crash with the following exception when trying to access it
```
  File "/home/update/updater/app.py", line 82, in get_device_list
    return builds.keys()
AttributeError: 'list' object has no attribute 'keys'
```

2018-04-15 12:31 UTC, fourkbomb requested changes
I'm not convinced that this is really a case we need to handle: the actual mirrorbits-api will always return at least an empty dictionary, so probably the "right" fix would just be to make your empty builds.json contain `{}`. 

FWIW: Python's `json` module refuses to load an empty string for me.

2018-04-15 12:31 UTC, fourkbomb commented on app.py
> +        return get_builds.keys()
`get_builds()`

2018-04-15 12:45 UTC, Stricted commented
im using php to generate the builds.json

thats the way PHP generates an empty json string
https://3v4l.org/Jr3Kd

i just came across this when setting up the updater when no builds where there yet
im fine with abandoning this

2018-07-08 05:15 UTC, zifnab06 commented
That's because it's not an array - the data structure is a map of device codenames to build blobs. I don't think we need this.

2018-07-08 05:15 UTC, closed without merging